version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
    networks:
      - app-network
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: . # Build image from local Dockerfile
    # restart: unless-stopped
    env_file: ./.env
    environment:
      DB_HOST: db
      DB_PORT:     "${DB_PORT}"
      DB_USER:     "${DB_USER}"
      DB_PASSWORD: "${DB_PASS}"
      DB_NAME:     "${DB_NAME}"
    ports:
      - "3000:3000" # Expose port 3000 on host
    depends_on:
      - db # Wait until database service is loaded
    networks:
      - app-network
networks: # Specify the network for bridging
  app-network:
    driver: bridge